Remove BH dependency
rstudio/httpuv pull request #297
Opened 2021-03-24 01:50 UTC by jcheng5

utils.h still imports boost/date_time.hpp

2021-03-24 20:42 UTC, wch commented on src/utils.h
> +    &g.tm_mday, &g.tm_mon, &g.tm_year, &g.tm_hour, &g.tm_min, &g.tm_sec
This use of `sscanf` makes me nervous. See https://stackoverflow.com/questions/9457325/how-to-use-sscanf-correctly-and-safely

Maybe we can use `std::stoi`?

2021-03-24 21:02 UTC, wch commented on src/utils.h
> +    &g.tm_mday, &g.tm_mon, &g.tm_year, &g.tm_hour, &g.tm_min, &g.tm_sec
Here's a rough sketch I tested out using cpp11, but obviously you'd just need to do this with C++. Note that it would need a try-catch, since this function can be called on the background thread.

```R
library(cpp11)
cpp_function('integers parse_date(std::string s) {
  writable::integers out(6);

  int pos = s.find(" ");
  out[0] = std::stoi(s.substr(0, pos));
  
  s = s.substr(pos + 1);
  pos = s.find(" ");
  out[1] = std::stoi(s.substr(0, pos));

  s = s.substr(pos + 1);
  pos = s.find(" ");
  out[2] = std::stoi(s.substr(0, pos));

  s = s.substr(pos + 1);
  pos = s.find(":");
  out[3] = std::stoi(s.substr(0, pos));
  
  s = s.substr(pos + 1);
  pos = s.find(":");
  out[4] = std::stoi(s.substr(0, pos));
  
  s = s.substr(pos + 1);
  out[5] = std::stoi(s);
  
  return out;
}')

parse_date("21 10 2015 07:28:00")
#> [1]   21   10 2015    7   28    0

parse_date("21 10 2015 07:28:a")
#> Error: stoi: no conversion
```

2021-03-26 20:17 UTC, wch commented on src/utils.h
> +    &g.tm_mday, &g.tm_mon, &g.tm_year, &g.tm_hour, &g.tm_min, &g.tm_sec
I did a little research and I think this should work:

```C++
  std::istringstream date_ss(date_str);
  date_ss >> std::get_time(&t, "%d %m %Y %H:%M:%S");
  if (date_ss.fail()) {
    return 0;
  }
```

Reference: https://en.cppreference.com/w/cpp/io/manip/get_time

2021-03-29 17:05 UTC, jcheng5 commented on src/utils.h
> +    &g.tm_mday, &g.tm_mon, &g.tm_year, &g.tm_hour, &g.tm_min, &g.tm_sec
@wch Nice! Does this need a try/catch?

2021-03-29 18:33 UTC, wch commented on src/utils.h
> +    &g.tm_mday, &g.tm_mon, &g.tm_year, &g.tm_hour, &g.tm_min, &g.tm_sec
I'm not entirely sure. It says [here](https://www.cplusplus.com/reference/iomanip/get_time/) that `get_time` can throw an exception, but I think something would have to be set up explicitly for that to occur:

> If the operation sets an internal state flag on the stream that was registered using its member exceptions, the function throws an exception of type ios_base::failure.

I found an example on SO where `get_time` throws an exception, but it seems like weird case:

> https://stackoverflow.com/questions/31030446/stdget-time-fails-at-midnight-or-noon-using-i-format-specifier

Just to be safe, I think we should use a try-catch.

2021-03-30 19:50 UTC, jcheng5 commented
`get_time` does seem much, much better! Thanks for the tip.

For testing, I tried replacing the locale (`"C"`) with a locale that is not installed, and that caused an exception; the `try`/`catch(...)` catches that exception. I also tried replacing the locale with a valid locale in a different language, and that caused the parsing to fail gracefully (which confirms that `get_time` does respect the imbued locale).

2021-03-30 20:18 UTC, wch commented
To answer my own question: the day of week gets put in the `tm` object:

```R
cpp11::cpp_source(
  code = '
#include <cpp11.hpp>
#include <sstream>
#include <iomanip>

using namespace cpp11;

[[cpp11::register]]
cpp11::integers datetest(std::string date) {
  std::tm t = {};

  std::istringstream date_ss(date);
  date_ss >> std::get_time(&t, "%a, %d %b %Y %H:%M:%S GMT");
  return writable::integers({
    t.tm_isdst,
    t.tm_yday,
    t.tm_wday,
    t.tm_year,
    t.tm_mon,
    t.tm_mday,
    t.tm_hour,
    t.tm_min,
    t.tm_sec
  });
}
')

datetest("Tue, 30 Mar 2021 15:14:00 GMT")
#> [1]   0   0   2 121   2  30  15  14   0
datetest("Wed, 30 Mar 2021 15:14:00 GMT")
#> [1]   0   0   3 121   2  30  15  14   0
```

But I think it gets ignored for date-time comparisons later on.

2021-03-30 20:20 UTC, wch commented on DESCRIPTION
>  SystemRequirements: GNU make
```suggestion
SystemRequirements: GNU make, C++11
```

2021-03-30 20:22 UTC, wch commented on NEWS.md
> +* Remove BH dependency. (#297)
```suggestion
* Remove BH dependency. httpuv now requires a compiler which supports C++11. (#297)
```

2021-03-30 21:21 UTC, wch commented
As of gcc 4.9.3 (which I believe is the version included with rtools 3.5), `get_time` is not implemented. This is item 27.7 in the table here: https://gcc.gnu.org/onlinedocs/gcc-4.9.3/libstdc++/manual/manual/status.html

2021-03-31 14:24 UTC, wch commented on src/utils.cpp
> +bool str_read_lookup(std::istream* input, size_t bytes, const char** values, int* pRes) {
No need to change this, but just a question. This could work with something like the following, right?

```C++
std::vector<std::string> MONTHS {"Jan", "Feb", "Mar", "Apr", "May", "Jun",
                                 "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" };


bool str_read_lookup(std::istream* input, std::vector<std::string> values, int* pRes) {
  ...
}
```

2021-03-31 14:25 UTC, wch requested changes
One piece of code that should be changed, but otherwise looks good.

2021-04-01 07:55 UTC, jcheng5 commented on src/utils.cpp
> +bool str_read_lookup(std::istream* input, size_t bytes, const char** values, int* pRes) {
I didn't know about that, that's pretty nice!

2021-04-01 15:51 UTC, merged